name: CI

on:  
  push:
    branches:
      - '*'
jobs:
  test-gcp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: generate RANDOM unique variable based on timestamp
      run: echo RANDOM=test-$(date +%s) >> $GITHUB_ENV
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        # GCP_CREDENTIALS is minified JSON of service account
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configure gcloud
      uses: 'google-github-actions/setup-gcloud@v0'

    # - name: 'Create Node Pool'
    #   run: 'gcloud container node-pools create ${{ env.RANDOM }} --cluster=${{ secrets.CI_CLUSTER_NAME }} --num-nodes=1 --zone=${{ secrets.CI_ZONE_NAME }} --machine-type=n1-standard-16'

    - name: Configure kubectl
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        #Run command: base64 ~/<account_id>.json
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.CI_CLUSTER_NAME }}
        ZONE_NAME: ${{ secrets.CI_ZONE_NAME }}
      with:
        args: get pods

    - name: Configure kubectl
      run: gcloud container clusters get-credentials ${{ secrets.CI_CLUSTER_NAME }} --zone ${{ secrets.CI_ZONE_NAME }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build docker
      run: cd tests && make docker

    - name: Push docker
      run: cd tests && make push

    - name: Run tests
      run: cd tests && make run test_name=TestSmeshing
    
    # - name: 'Delete Node Pool'
    #   run: 'yes | gcloud container node-pools delete ${{ env.RANDOM }} --cluster=${{ secrets.CI_CLUSTER_NAME }} --zone=${{ secrets.CI_ZONE_NAME }}'
